Repository stakecube/StakeCubeProtocol, pull requests merged in 2021-07, with the labels that each got.

#9 [Init] [UI] Refactor Fullnode/Lightwallet + Init
  main.js
  src/index.js
Labels: enhancement

#11 [API] Refactor index.js into route files
  src/api/activity.js
  src/api/blockchain.js
  src/api/tokens.js
  src/api/wallet.js
  src/index.js
Labels: enhancement

#15 [API] Add new API config options
  src/api/activity.controller.js
  src/api/activity.routes.js
  src/api/blockchain.controller.js
  src/api/blockchain.routes.js
  src/api/permissions.js
  src/api/tokens.controller.js
  src/api/tokens.routes.js
  src/api/wallet.controller.js
  src/api/wallet.routes.js
  src/index.js
  src/network.js
Labels: enhancement

#17 [API] Reduce redundant Token data
  src/token.js
Labels: enhancement

#12 [docs] Add initial SCP documentation
  docs/api/activity.md
  docs/api/blockchain.md
  docs/api/tokens.md
  docs/api/wallet.md
  docs/development/contributing.md
  docs/development/dependencies.md
  docs/guides/de/installation.md
  docs/guides/en/installation.md
  docs/misc/scp-configurations-file.md
  docs/protocols/scp-1.md
  docs/protocols/scp-2.md
  docs/readme.md
  docs/release-notes/release-notes-1.1.3-genesis.md
  docs/release-notes/release-notes-1.1.4.md
Labels: documentation

#20 [Init] Enhanced init, troubleshooting & auto-reconnect.
  src/database/index.js
  src/index.js
Labels: enhancement

#21 [API] Add IO module for on-chain read/write ops
  src/api/io.controller.js
  src/api/io.routes.js
  src/index.js
Labels: enhancement

#22 [API] Improve controller module loading
  src/api/activity.routes.js
  src/api/blockchain.routes.js
  src/api/io.routes.js
  src/api/tokens.routes.js
  src/api/wallet.routes.js
Labels: enhancement

#25 [API] [IO] Move /write/ to binary POSTs
  src/api/io.controller.js
  src/api/io.routes.js
  src/index.js
Labels: enhancement

#23 [docs] guides updated to indexed BS on SCP repo
  docs/guides/de/installation.md
  docs/guides/en/installation.md
Labels: documentation

#24 [docs] add detailed 'io' api description
  docs/api/io.md
  docs/api/wallet.md
  docs/misc/scp-configurations-file.md
  docs/readme.md
Labels: documentation

#27 [API] Fix multiple GUI Lightwallet issues + GetStakingStatus
  docs/api/io.md
  docs/api/tokens.md
  docs/api/wallet.md
  public/index.html
  scripts/network.js
  src/api/tokens.controller.js
  src/api/tokens.routes.js
  src/api/wallet.controller.js
  src/api/wallet.routes.js
  src/network.js
Labels: documentation, enhancement

#26 [SCP] [Consensus] SCP-2 Staking + Indexing Upgrade
  public/index.html
  src/index.js
  src/token.js
  src/upgrades.js
Labels: enhancement

#28 [UI] Add SCP InstantSend into the GUI
  public/index.html
  scripts/network.js
  src/api/tokens.controller.js
  src/api/tokens.routes.js
Labels: enhancement
